## Acerca de esta serie de libros de investigación

### Enfoque

Con esta convocatoria, la Comisión Nacional Asesora para la Promoción de la Ciencia, tecnología, e Innovación en Gestión del Riesgo de Desastres y la Unidad Nacional para la Gestión del Riesgo de Desastres, que en el marco en la Ley 1523 de 2012 y en el ejercicio de la promoción de la investigación, continúan desarrollando una estrategia de divulgación de nuevo conocimiento derivado de procesos de investigación sobre la gestión del riesgo de desastres en el país. Se espera que el libro se utilice como fuente de consulta para la toma de decisiones informadas en la gestión del riesgo de desastres y para la promoción de actividades de ciencia, tecnología e innovación ante el Sistema Nacional de Gestión del Riesgo de Desastres.

::: callout-important
## Encuentre aquí las Instrucciones para autores

[Ver instrucciones para autores](instrucciones-autor.qmd)
:::

### Temáticas

La ciencia de los desastres es un área de investigación creciente en Colombia e indispensable para responder a los desafíos que presentan los fenómenos amenazantes en el país y sus complejas interacciones. A través de la Comisión Asesora se invita investigadores, estudiantes, contratistas del Estado, profesionales independientes, industria, sociedad civil organizada, organizaciones no gubernamentales, e instituciones en general a presentar capítulos de investigación en gestión del riesgo de desastres para construir un libro editado que contendrá capítulos sobre las siguientes temáticas:

-   Procesos y subprocesos de la gestión del riesgo de desastres: Conocimiento del riesgo de desastres: identificación y caracterización de escenarios de riesgo. Análisis y evaluación de la amenaza, la vulnerabilidad y el riesgo.

-   Monitoreo del riesgo. Comunicación del riesgo. Percepción del riesgo, educación en gestión de riesgos. Reducción del riesgo de desastres: intervención prospectiva y correctiva del riesgo, protección financiera.

-   Manejo de desastres: preparación para la respuesta, ejecución para la respuesta, ejecución para la recuperación, preparación para la recuperación, recuperación post desastres (incluyendo la enfocada en ecosistemas), y logística de la ayuda humanitaria.

Temas transversales y emergentes como:

-   Apropiación social del conocimiento, innovación social, animales en la GRD, innovación educativa, soluciones basadas en la naturaleza, gobernanza del riesgo de desastres, rol de las entidades territoriales, corresponsabilidad de los actores en la gestión del riesgo de desastres, generación de datos, y análisis prospectivo.

-   Ordenamiento territorial (p.ej. casos exitosos y no exitosos desde los municipios), justicia climática, evaluación de daños y pérdidas, migración y movilidad, y reasentamientos.

-   Cambio climático y su relación con la gestión del riesgo, relación entre salud y clima, síntesis o discusiones derivadas de las Conferencia de la ONU sobre Cambio Climático (COP).

También nos interesa formalizar el nuevo conocimiento de GRD desde y relacionado con las comunidades locales, juventudes, pueblos o grupos étnicos, indígenas, afrocolombianos, raizales, palenqueros y gitanos, y sociedad civil organizada. Esto incluye prácticas comunitarias de GRD desde los saberes y conocimientos tradicionales, ancestrales, étnicos, o campesinos.

Alentamos a postular nuevo conocimiento y experiencias de la incorporación de la GRD desde los sectores como defensa, transporte, vivienda, agricultura, salud, comunicaciones, infraestructura, o educación, entre otros. El libro presentará a la comunidad profesional, académica y científica los resultados de investigaciones originales en gestión del riesgo de desastres que tienen un impacto territorial, sectorial o comunitario.

Se espera que este nuevo conocimiento impacte en investigaciones futuras, convocatorias de ciencia, la toma de decisiones y la política pública en gestión de riesgo de desastres. El libro seguirá estándares editoriales de alta calidad y seguirá los estándares solicitados como un libro de investigación para Minciencias.

### Caracteristicas del libro de investigaciones

El producto será un libro editado por capítulos en formato digital editado por la Comisión Asesora. La publicación tendrá un ISBN y se divulgará a través de los medios de la UNGRD, mediante el Centro de Documentación en Gestión del Riesgo de Desastres (CEDIR) de la UNGRD y otros canales de instituciones del Sistema Nacional de Gestión del Riesgo de Desastres (SNGRD).

Las dos ediciones anteriores del libro se han convertido en un punto de encuentro de la comunidad profesional, técnica, y científica del país. Con esta nueva edición,  buscamos que el libro se convierta no solo en un instrumento de consulta y gestión para la toma de decisiones, sino que sea un espacio dónde presentar nuevo conocimiento de manera novedosa y complementaria a las revistas de investigación.

Las herramientas de inteligencia artificial nos ubican en una nueva era. Así, la Comisión Asesora invita a utilizar estas nuevas herramientas y metodologías en la generación de los capítulos, y  se incluye en las instrucciones de autor una nueva sección que solicita informar cómo estas herramientas se han empleado. 

Los miembros de la Comisión Asesora actuarán como el Comité Editorial quienes determinarán si los capítulos pueden o no incluirse en el libro y si son adecuados para su envío a pares revisores; también sugerirán modificaciones si son oportunas. El Equipo editorial UNGRD verificará el cumplimiento de la guía de autor de los documentos. El libro tendrá un proceso de revisión por pares doble ciego (ni los revisores ni los autores conocen entre sí sus identidades) y cada capítulo tendrá al menos dos pares revisores. Los revisores evaluarán la originalidad del conocimiento del trabajo, la pertinencia en la temática del libro, la calidad de redacción y el impacto de las figuras. La decisión se realizará dentro de los menores tiempos posibles. 

Los manuscritos que se postulen deben ser originales y por lo tanto no pueden estar simultáneamente en proceso de publicación en otras revistas o libros científicos. Para que Minciencias reconozca al libro como producto de investigación se deben cumplir los requisitos que se describen en el Cuadro 1 (ver Modelo de medición de grupos Minciencias).

+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Cuadro 1.** Características para validar un capítulo de libro como un producto de investigación.                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| -   Publicación original e inédita que es resultado de investigación y que forma parte de un libro de colaboración conjunta. Se entiende por “capítulo de libro” cualquier parte principal del mismo que se pueda asumir como un texto que presenta un tema por abordar, que lo desarrolla y que llega a conclusiones, de tal manera que presente una unidad temática en sí mismo.                                                                                                                                                                 |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| -   Además, tienen un autor -o autores- identificables, que aparecen claramente bien sea en el índice, en el inicio o en el fin del capítulo. Debe hacer parte de un libro, que se entienda como compilación, o como edición académica o como obra colectiva. No se consideran como “capítulos”, presentaciones de compilaciones, prólogos o introducciones que no respondan a la definición anteriormente referida. Se excluyen también epílogos o conclusiones, anexos, índices, bibliografías, dedicatorias y/o reseñas biográficas de autores. |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| -   El libro que contiene este capítulo ha sido evaluado por parte de dos pares académicos; ha sido seleccionado por sus cualidades científicas como una obra que hace aportes significativos al conocimiento en su área y da cuenta de una investigación completamente desarrollada y concluida. Además, esta publicación ha pasado por procedimientos editoriales que garantizan su normalización bibliográfica y su disponibilidad.                                                                                                             |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| -   En esta definición de capítulo en libro resultado de investigación, no están contempladas las siguientes publicaciones, aún en el caso de que hayan pasado por un proceso de evaluación por pares académicos, resúmenes; presentación de hallazgos de investigaciones no concluidas, libros de apoyo pedagógico, libros de enseñanza de idiomas, libros de texto, entrevistas, manuales, guías, cartillas, ensayos, ponencias, memorias de eventos, libros de poesía, novelas, libros de divulgación, ni libros de formación.                  |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| **Anexo 1. Requerimientos de existencia en convocatoria de medición de grupos.**                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| -   Los autores de capítulos deben individualmente realizar este paso en sus instituciones.                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| -   Certificación emitida por el representante legal o (quien haga sus veces) de la entidad que avala el Grupo de Investigación, desarrollo tecnológico o de Innovación y el currículo en el que declare que una vez revisados los soportes del libro se puede validar como “Libro resultado de Investigación”                                                                                                                                                                                                                                     |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| -   Certificación emitida por el representante legal o (quien haga sus veces) de la entidad que avala el Grupo de Investigación, desarrollo tecnológico o de Innovación y el currículo en el que mencione en los créditos de la obra a los patrocinadores o financiadores de la publicación o del proyecto de investigación del cual se derivó el libro.                                                                                                                                                                                           |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

La diagramación incluirá elementos de consulta rápida como cajas de mensajes. Estas cajas pueden resumir un marco legal o normativo, o pueden contener un glosario de conceptos clave. Las cajas también pueden contener listas de direcciones web, o listas de elementos relevantes para la narrativa del capítulo. También al final del texto principal se utilizarán cajas de mensaje a casa, que puede ser una recomendación para tomar decisiones, los aspectos más destacados, la descripción de un vacío de conocimiento, o una necesidad futura.

## **Derechos de autor, archivo y permisos**

Antes de la publicación, se pedirá a todos los autores firmar una declaración explícita de transferencia completa de los derechos de autor del capítulo como producto de dominio público (incluidas todas las tablas y figuras) necesarios para divulgar la publicación. Antes de iniciar el proceso de publicación por favor asegúrese que su institución puede ceder los derechos de autor a la UNGRD bajo licencia Creative Commons con atribución NoComercial-SinDerivadas 2.5 Colombia.

### **Proceso editorial**

El proceso editorial de evaluación y revisión de capítulos tendrá cuatro pasos:

1.  Equipo editorial UNGRD recibe el capítulo y hace control de calidad, en el cual verificará el cumplimiento de guía de autor.

2.  Si el capítulo aprueba el control de calidad, se enviará el capítulo para evaluación a un experto de la Comisión Asesora. Si aprueba la evaluación, el comité sugerirá un conjunto de potenciales revisores al Equipo editorial UNGRD.

3.  El equipo editorial de UNGRD se encargará de comunicarse con los revisores, de recibir las revisiones y de enviarlas a los autores, hasta alcanzar la aprobación del capítulo.

4.  El equipo de editorial UNGRD mantendrá informado a los editores de la Comisión Asesora del estado avance de los capítulos hasta culminar la revisión por pares.

5.  El equipo editorial envía los capítulos aprobados para diagramación, pruebas de galera y culminar el proceso de publicación.