---
title: "Instrucciones para autores"
toc: true
---

# Instrucciones para los autores

Esta sección contiene la información necesaria para preparar su capítulo de investigación y postularlo como capítulo original e inedito. Todo el proceso editorial sigue estándares nacionales e internacionales de comunicación y estilo científico.

## Revisión por pares

Cada capítulo del libro lo revisarán mínimo dos pares. Solicitamos a los autores sugerir tres potenciales pares revisores (nombre, correo-e y afiliación) sin conflicto de intereses. Se aplicará un sistema de revisión doble ciego en el cual ni los revisores ni los autores conocen entre sí sus identidades. Los revisores evaluarán la originalidad del conocimiento del trabajo, la pertinencia para la temática del libro, la calidad de redacción y el impacto de las figuras.

## Estílo científico

Seguimos las directrices del manual de estilo Manual de publicaciones de la American Psychological Association, cuarta edición, en los Capítulos 4 a 7 ([enlace](https://books.google.com.co/books?id=kf5tEAAAQBAJ)). Para aspectos más específicos, seguiremos las pautas del Scientific Style and Format: The CSE Manual for Authors, Editors, and Publishers ([enlace](https://www.scientificstyleandformat.org/Home.html)). También, consideraremos otras fuentes de referencia como The Chicago Manual of Style ([enlace](https://www.chicagomanualofstyle.org/book/ed17/frontmatter/toc.html)), así como artículos y libros de revistas internacionales de investigación. Para resolver dudas idiomáticas, se recomienda consultar el sitio de la Real Academia Española (RAE).

## Manuscrito

El texto del capítulo debe presentarse en español, en hojas tamaño carta, a una sola columna, con numeración de filas continua en el lado izquierdo, utilizando la fuente Times New Roman tamaño 12, con interlineado de 1.5 y sin justificación. Las páginas deben estar numeradas en la parte inferior. Se recomienda no exceder las 70 referencias bibliográficas. La siguiente plantilla de Word guía la construcción del capítulo (<https://bit.ly/plantilla-libroGRD>). 

El archivo de texto debe contener la siguiente información:

**Título:** No debe tener una extensión mayor a 30 palabras.

**Autores y afiliación:** Nombres y afiliaciones de todos los autores. Un autor puede tener varias afiliaciones. Si un autor se trasladó, también se puede indicar la afiliación actual. El autor de contacto debe identificarse al final con un asterisco y con una dirección de correo electrónico.

**Resumen:** Sugerimos presentar un resumen estructurado (e.g. [Summary paragraph](https://www.nature.com/documents/nature-summary-paragraph.pdf)) de máximo 300 palabras en español y en inglés.

**Palabras clave:** Incluya cinco palabras clave en español.

**Título, Resumen y Palabras clave en inglés.**

**Texto del capítulo:** El número de palabras en el texto principal no debe ser mayor de **ocho mil palabras**. No exigimos una estructura narrativa predefinida. Alentamos seguir una estructura narrativa continua tipo artículo científico como Introducción, Resultados, Discusión, Conclusión, y por último Materiales y Métodos (IRDCaM). Así mismo, el texto puede dividirse en secciones e iniciar con una Introducción General, seguido del Tema 1 (RDC),  Tema 2 (RDC), conclusión general, y por último Materiales y Métodos. Numere todas las secciones y subsecciones comenzando por la introducción. Las secciones principales deben ir en mayúsculas (p.ej. 1. INTRODUCCIÓN; 2. TEMA PRINCIPAL 1; 3. TEMA PRINCIPAL 2; 4. CONCLUSIONES). 

Por favor emule estructuras de capítulos del libro Investigaciones en gestión del riesgo de desastres para Colombia. Avances, perspectivas y casos de estudio. 

**Figuras y tablas:** El capítulo debe contener al menos una figura. No tenemos pautas específicas para el diseño de las figuras y tablas, pero sugerimos seguir la Norma APA. Acompañe las figuras y tablas con una leyenda. Inserte las figuras como elementos de baja resolución en la ubicación que corresponde dentro del texto. En la diagramación el diseñador utilizará las imágenes en alta resolución. 

Si utiliza figuras de fuentes no propias, debe obtener permiso para reutilizar y modificar las figuras antes de enviar su manuscrito. Póngase en contacto directamente con los editores de la publicación fuente para obtener permiso de reutilizar las figuras. Guarde en su archivo el correo que otorga el permiso enviado por la fuente (e.g., [www.copyright.com](http://www.copyright.com)). La fuente de donde obtuvo el material debe acreditarse al final de la figura con el texto: “con autorización de”. Si una figura tiene derechos de autor Creative Commons (CC) o está en el dominio público, es posible que no necesite permiso para usarlo, pero en general todavía se requiere la atribución de la fuente.

Para las dimensiones y diseño de figuras y gráficas, puede seguir las pautas de la American Geophysical Union, al igual que otras como:

-   <https://publications.agu.org/author-resource-center/graphics/>

-   <https://www.data-to-viz.com/>

-   <https://serialmentor.com/dataviz/>

Las figuras deberán entregarse como archivos independientes en formatos vectoriales o raster como .eps, .pdf, .png o tif (resolución mínima 300 dpi). Nombre los archivos con el número de la figura correspondiente. Las tablas deberán insertarse dentro del texto y formatearlo con la herramienta de tablas de Word o equivalente. 

Para guiarse en la presentación de figuras y tablas por favor revise los capítulos del libro Investigaciones en gestión del riesgo de desastres para Colombia. Contribuciones locales, regionales y nacionales.

**Cajas de mensajes en texto principal:** Se debe incluir al menos dos cajas de mensajes en el texto principal (máximo 10 cajas). Estas cajas se emplearán a lo largo del texto como objeto de consulta rápida al lector, aspecto que usualmente aumenta la citación de los textos. Estas cajas pueden resumir un marco legal o normativo. También pueden contener un glosario de conceptos clave, listas de recursos web, listas de literatura clave, discutir brevemente un tema llamativo, o listas de elementos relevantes para la narrativa del capítulo. Son equivalentes a una nota al pie de página. Inserte estas cajas como una tabla de 1×1 aproximadamente en la ubicación que corresponde.

**Caja final de mensaje a casa:** Para aumentar el uso del libro por la comunidad profesional, al final del texto principal solicitamos incluir solamente dos cajas de mensaje (ver Fig. 3). La caja de puntos clave (máximo 8 puntos)  es obligatoria y debe incluirse otra caja con  recomendaciones para tomar decisiones, necesidades futuras o preguntas por resolver.

**Materiales y métodos:** La sección de materiales y métodos se colocará al final del capítulo y debe escribirse de la manera más concisa posible, pero debe contener todos los elementos necesarios para interpretar y replicar los resultados. En el estilo moderno de comunicación científica se traslada como Información Suplementaria (IS) algunos elementos de los Materiales y Métodos. Estos elementos por su tamaño o características no podrán publicarse en el libro y sugerimos se publiquen en repositorios digitales.

**Información suplementaria:** Para garantizar que los resultados sean FAIR ([Findable, Accessible, Interoperable and Reusable](https://www.nature.com/articles/sdata201618)) y se apoyen las políticas de ciencia abierta, invitamos a incluir la Información Suplementaria (IS) como enlaces a [repositorios](https://www.nature.com/sdata/policies/repositories) como Zenodo o similares. Estos archivos pueden ser tablas de datos, archivos SIG, scripts de código (p.ej. Jupyter notebooks o proyectos en Git), vídeos o similares. En los repositorios digitales la IS debe contener información del título del Capítulo y los autores con sus afiliaciones. Al citar tablas o figuras de la IS, por favor coloque la letra S como Fig. S1 o Tabla S1. No existirán límites de extensión o tamaño del SI. Incluya en el texto principal el número DOI que genera el repositorio. No sugerimos una estructura predeterminada al SI.

**Agradecimientos:** Los agradecimientos deben ser breves. De tenerlos, incluya los nombres de los financiadores con los códigos de financiación o de proyecto.

**Contribución de autoría CRediT:** Por favor incluya la descripción de la contribución de autoría siguiendo el estándar CRediT. Por ejemplo:

Conceptualización: APR, AN, MFG. Metodología: APR. Redacción de primera versión: APR. Escritura. Revisión y edición de segunda versión: APR, AN, MFG. Figuras y tablas: APR, AN, MFM. Administración de proyecto: APR, AN. Búsqueda de evidencia: APR, AN, MFG.

**Identificación de autor:** Por favor incluya una lista de los enlaces a perfiles en Google Académico, ORCID o CVLAC.

Autor 1   orcid.org/0000-0000-0000-0000 

Autor 2   https://scholar.google.com/citations?user=n000aaaAAAAJ

Autor 3   http://scienti.colciencias.gov.co:8081/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0000000

**Conflicto de intereses:** Declare si existe conflicto de intereses.

**Uso de herramientas de inteligencia artificial:** Los autores pueden utilizar herramientas de Inteligencia Artificial (IA) en el proceso de redacción previo al envío, exclusivamente con el propósito de mejorar el lenguaje y la legibilidad de su capítulo, y siempre bajo la condición de incluir una declaración, siguiendo nuestras instrucciones de la Guía del Autor. Los editores encontrarán la declaración “de IA generativa en la escritura científica” al final del artículo. **Declaración:** "Durante la preparación de este capítulo, los autores utilizaron \[nombre de la herramienta / versión / servicio\] con el fin de \[motivo\].”  Como también "Durante la preparación de este capítulo, los autores no utilizaron ninguna herramienta de inteligencia artificial.”

Destacamos que la IA y las tecnologías asistidas por IA no deben considerarse como autores o coautores, ni mencionarse como tales. La autoría conlleva responsabilidades y tareas que sólo pueden asumirse y ejecutarse por humanos. Tras emplear esta herramienta o servicio, los autores revisarán y editarán el contenido según fuese necesario, asumiendo la completa responsabilidad por el contenido de la publicación.

**Reglas de citación en texto:** Para la primera versión no se requiere aplicar el estilo de citación de referencias bibliográficas. Para la versión final se seguirá el estilo de citación en texto tipo Vancouver \[1\] en el cual las referencias se numeran secuencialmente a medida que aparecen en el texto, tablas o las leyendas de figuras. Se dejará un espacio entre la última letra y el paréntesis cuadrado. Si se emplean varias referencias se separarán por una coma sin espacio \[1,2,19\]. Se otorga solo una referencia por cada número consecutivo. Si se prefiere citar al autor, cite los apellidos sin año (p.ej. Rodriguez & White \[14\] y Pérez et al. \[54\]). No se emplean cursivas en la abreviatura et al. No se utilizarán notas al pie (use cajas de mensajes). Se permiten hasta 70 referencias bibliográficas. 

**Reglas de citación en bibliografía:** Se seguirán las pautas de citación de Manual de publicaciones de la American Psychological Association, cuarta edición (Capítulos 8–11). La plantilla de estilo APA existe para los administradores de referencias Mendeley y EndNote. De estar disponibles, emplee siempre los códigos Doi. 

**Marcaje de texto para índice temático:** En la última versión y antes de enviar a diagramación, para construir el índice temático al final del libro, agradecemos a los autores marcar al menos diez conceptos clave de su texto principal. Para orientar al equipo editorial en su ubicación y página, estos conceptos deben marcarse en color verde. Si lo desea, puede insertar el  marcaje siguiendo la ruta: seleccionar el concepto en el texto e ir a  Referencias \> Marcar entrada \> Marcar \> Cerrar. Notará que Word agrega un marcaje de índice a las palabras seleccionadas (p.ej.{ XE "concepto"}). Se insertará el índice al final del texto al culminar el documento maestro del libro.

## Lista de verificación

**Antes de enviar aplique la siguiente lista de verificación:**

1.  Archivo editable del manuscrito en Microsoft Word.
2.  El texto principal contiene el título del capítulo, nombre(s) de autor(es) y afiliación(s).
3.  Después de la información de afiliación se incluye el autor de contacto y su dirección de correo electrónico. 
4.  Resumen estructurado de máximo 300 palabras en español e inglés.
5.  Palabras clave: hasta cinco en español e inglés.
6.  Encabezados claramente formateados en las secciones de todo el texto.
7.  Figuras y tablas con su propia leyenda en el texto. 
8.  Ecuaciones insertadas con editor de ecuaciones.
9.  Las figuras se incluyeron dentro del texto en el lugar donde corresponde. 
10. Las tablas se incluyeron dentro del texto en el lugar donde corresponde con la herramienta de insertar tablas de MS Word.
11. Se incluyen al menos dos cajas de mensaje en el texto principal y se incluyeron dentro del texto en el lugar donde corresponde con la herramienta de insertar tablas de MS Word.
12. Se incluyen dos cajas finales de mensaje a casa: la de puntos clave y otra como las necesidades futuras, preguntas a resolver, o recomendación para toma de decisiones.
13. Se incluye la información de identificación de autor como perfil de Google Académico, ORCID o CVLac. 
14. Si se incluye Información Suplementaria, incluir el DOI.
15. La literatura citada en el texto utiliza paréntesis cuadrados (la primera versión no requiere aplicar el estilo de citación de referencias bibliográficas)
16. La literatura citada en bibliografía aparece numerada acorde a su posición consecutiva dentro del texto y cumple las normas de estilo APA. El número máximo de referencias no supera las 70 referencias (la primera versión no requiere aplicar el estilo de citación de referencias bibliográficas).
17. Se verificó el uso correcto de acrónimos, escritura de números, presentación de estadísticos, presentación y numeración de ecuaciones, uso de mayúsculas y el uso correcto de la voz pasiva.
18. Se marcaron en color verde hasta 10 conceptos para incluir en el índice temático.
19. Archivos de figuras de alta resolución o vectoriales.
20. Las figuras cuentan con autorizaciones de derechos de autor o son de uso libre. Se ha dado el crédito necesario donde corresponde.

---

[← Acerca de esta serie](acerca-de.qmd)